// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/toast-home/AirbnbStyle.tsx": () => import("../components/mockups/toast-home/AirbnbStyle.tsx"),
  "./components/mockups/solo-journey/SoloJourney.tsx": () => import("../components/mockups/solo-journey/SoloJourney.tsx")
};
